// App-owned facade for hono-decks.
// This file is safe to edit. `src/generated/decks.ts` is generated by `hono-decks compile`.
import { mergeDecksRouterOptions, type DecksRouterOverrides } from "hono-decks";
import decksConfig, { type DecksConfigEnv } from "./decks.config";
import { decks } from "./generated/decks";

export const deckMountPath = decksConfig.mountPath ?? "/decks";
export const deckSource = decksConfig.source?.(decks.source) ?? decks.source;

export function createDecksRouter(options: DecksRouterOverrides<DecksConfigEnv> = {}) {
  return decks.router(
    mergeDecksRouterOptions(
      { ...decksConfig.router, source: deckSource },
      options,
    ),
  );
}
