// App-owned facade for @hono/decks.
// This file is safe to edit. `src/generated/decks.ts` is generated by `hono-decks compile`.
import type { DecksRouterOverrides } from "@hono/decks";
import decksConfig from "./decks.config";
import { decks } from "./generated/decks";

export const deckMountPath = decksConfig.mountPath ?? "/decks";
export const deckSource = decksConfig.source?.(decks.source) ?? decks.source;

export function createDecksRouter(options: DecksRouterOverrides = {}) {
  return decks.router({
    ...decksConfig.router,
    ...options,
    source: options.source ?? deckSource,
  });
}
