// App-owned facade for @hono/decks.
// This file is safe to edit. `src/generated/decks.ts` is generated by `hono-decks compile`.
import type { DecksRouterOverrides } from "@hono/decks";
import { createSampleDeckSource } from "./decks.config";
import { decks } from "./generated/decks";

export const deckSource = createSampleDeckSource(decks.source);

export function createDecksRouter(options: DecksRouterOverrides = {}) {
  return decks.router({
    source: deckSource,
    ...options,
  });
}
