export {
  createDeckViewerParts,
  deckContext,
  defineDecks,
  decksRouter,
  deckMiddleware,
  serveDecksClientEntry,
  withR2Assets,
} from "./mod";
export type {
  DeckContextOptions,
  DeckContextVariables,
  DeckPageMeta,
  DeckTocItem,
  DeckViewerOptions,
  DeckViewerParts,
  DeckViewerRenderInput,
  DefinedDecks,
  DecksOptions,
  DecksRouterExtension,
  DecksRouterOptions,
  DecksRouterOverrides,
  DeckMiddlewareOptions,
  DeckRenderable,
  MaybePromise,
  R2AssetKeyInput,
  R2AssetSourceOptions,
  R2BucketLike,
  R2BucketResolver,
  R2ObjectBodyLike,
  R2ObjectHttpMetadataLike,
  ServeDecksClientEntryOptions,
} from "./mod";
