export { defineDecksConfig } from "./server/define-decks";
export type {
  ConfiguredDecks,
  DecksBuildConfig,
  DecksConfig,
  DecksRouterConfig,
} from "./server/define-decks";
export { createDeckPaths } from "./server/paths";
export type { DeckPaths } from "./server/paths";
export { createDeckViewerEmbed } from "./server/router";
export type {
  DeckBrowserRunBinding,
  DeckBrowserRunPdfOptions,
  DeckBrowserRunPngOptions,
  DeckContextVariables,
  DeckDevResolver,
  DeckDevResolverInput,
  DeckDocumentOptions,
  DeckDocumentPageOptions,
  DeckDocumentRenderInput,
  DeckDocumentSurface,
  DeckExportResolverInput,
  DeckExportOptions,
  DeckExternalEmbedContext,
  DeckExternalEmbedOptions,
  DeckExternalEmbedRenderInput,
  DeckExternalEmbedViewerOptions,
  DeckIndexPageInput,
  DeckIndexPageOptions,
  DeckIndexRenderInput,
  DeckPageMeta,
  DeckPresenterEnabledInput,
  DeckPresenterEnabledResolver,
  DeckPresenterViewerControlOptions,
  DeckTocItem,
  DeckRouteEnabled,
  DeckRouteEnabledResolver,
  DeckRouteSurface,
  DeckRouteSurfaceInput,
  DeckViewerControlDefaults,
  DeckViewerAvailablePages,
  DeckViewerDefaultControlItem,
  DeckViewerControlItem,
  DeckViewerControlItemRenderer,
  DeckViewerControlKey,
  DeckViewerControlRenderInput,
  DeckViewerControlSlotItems,
  DeckViewerControlsContext,
  DeckViewerControlsItemsResolver,
  DeckViewerControlsOptions,
  DeckViewerEmbed,
  DeckViewerEmbedOptions,
  DeckViewerExportPaths,
  DeckViewerLinkControlItem,
  DeckViewerOptions,
  DeckViewerPart,
  DeckViewerParts,
  DeckViewerRenderControlItem,
  DeckViewerRenderInput,
  DecksRouterExtension,
  DecksRouterOptions,
  DecksRouterPagesOptions,
  DecksRouterPresenterOptions,
  ResolvedDeckDocument,
} from "./server/router";
export { withR2Assets } from "./source/r2-assets";
export type {
  R2AssetKeyInput,
  R2AssetSourceOptions,
  R2BucketLike,
  R2BucketResolver,
  R2ObjectBodyLike,
  R2ObjectHttpMetadataLike,
} from "./source/r2-assets";
export type {
  AssetRef,
  CompileWarning,
  CompiledDeck,
  CompiledSlide,
  ComponentPlaceholder,
  DeckEntry,
  DeckFrontmatter,
  DeckKind,
  DeckManifest,
  DeckRequestContext,
  DeckSource,
  SlideFrontmatter,
  SlideTransition,
} from "./deck/model";
export { SLIDE_TRANSITIONS } from "./deck/model";
export { defineSlideComponents } from "./renderer/compiled-render";
export type {
  DeckRenderable,
  MaybePromise,
  SlideComponent,
  SlideComponentDefinition,
  SlideComponentInput,
  SlideComponentProps,
  SlideComponentRegistry,
} from "./renderer/compiled-render";
export type { DeckControlIconName } from "./renderer/control-icons";
