export { defineDecks, defineDecksConfig, mergeDecksRouterOptions } from "./server/define-decks";
export type {
  DecksConfig,
  DefinedDecks,
  DecksOptions,
  DecksRouterOverrides,
} from "./server/define-decks";
export { createDeckViewerEmbed, createDeckViewerParts, deckContext, decksRouter } from "./server/router";
export type {
  DeckBrowserRunBinding,
  DeckBrowserRunPdfOptions,
  DeckBrowserRunPngOptions,
  DeckContextOptions,
  DeckContextVariables,
  DeckDevResolver,
  DeckDocumentOptions,
  DeckDocumentPageOptions,
  DeckDocumentRenderInput,
  DeckDocumentSurface,
  DeckExportAuthorizeInput,
  DeckExportOptions,
  DeckExternalEmbedContext,
  DeckExternalEmbedOptions,
  DeckExternalEmbedRenderInput,
  DeckExternalEmbedViewerOptions,
  DeckIndexPageInput,
  DeckIndexPageOptions,
  DeckIndexRenderInput,
  DeckPageMeta,
  DeckPresenterEnabledInput,
  DeckPresenterEnabledResolver,
  DeckPresenterViewerControlOptions,
  DeckTocItem,
  DeckRouteEnabled,
  DeckRouteEnabledResolver,
  DeckRouteSurface,
  DeckRouteSurfaceInput,
  DeckViewerControlDefaults,
  DeckViewerDefaultControlItem,
  DeckViewerControlItem,
  DeckViewerControlItemRenderer,
  DeckViewerControlKey,
  DeckViewerControlRenderInput,
  DeckViewerControlSlotItems,
  DeckViewerControlsContext,
  DeckViewerControlsItemsResolver,
  DeckViewerControlsOptions,
  DeckViewerEmbed,
  DeckViewerEmbedOptions,
  DeckViewerExportPaths,
  DeckViewerLinkControlItem,
  DeckViewerOptions,
  DeckViewerParts,
  DeckViewerRenderControlItem,
  DeckViewerRenderInput,
  DecksRouterExtension,
  DecksRouterOptions,
  DecksRouterPagesOptions,
  DecksRouterPresenterOptions,
  ResolvedDeckDocument,
} from "./server/router";
export { serveDecksClientEntry } from "./server/client-entry";
export type { ServeDecksClientEntryOptions } from "./server/client-entry";
export { manifestDeckSource } from "./source/manifest-source";
export { withR2Assets } from "./source/r2-assets";
export type {
  R2AssetKeyInput,
  R2AssetSourceOptions,
  R2BucketLike,
  R2BucketResolver,
  R2ObjectBodyLike,
  R2ObjectHttpMetadataLike,
} from "./source/r2-assets";
export type {
  AssetRef,
  CompileWarning,
  CompiledDeck,
  CompiledSlide,
  ComponentPlaceholder,
  DeckEntry,
  DeckFrontmatter,
  DeckKind,
  DeckManifest,
  DeckRequestContext,
  DeckSource,
  SlideFragmentsMode,
  SlideFrontmatter,
  SlideTransition,
} from "./deck/model";
export { SLIDE_TRANSITIONS } from "./deck/model";
export {
  builtInSlideComponents,
  defineSlideComponents,
  renderCompiledDeck,
  renderCompiledDeckAsync,
  renderCompiledDeckPage,
  renderCompiledDeckPageAsync,
  renderCompiledSlide,
  renderCompiledSlideAsync,
} from "./renderer/compiled-render";
export type {
  DeckRenderable,
  MaybePromise,
  SlideComponent,
  SlideComponentDefinition,
  SlideComponentInput,
  SlideComponentProps,
  SlideComponentRegistry,
} from "./renderer/compiled-render";
export {
  controlIconLabel,
  renderControlIcon,
  renderControlIconHtml,
} from "./renderer/control-icons";
export type { DeckControlIconName } from "./renderer/control-icons";
